/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/nexus-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved Nexus public key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NexusPublicKey"];
                    };
                };
                /** @description Server error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NexusPublicKey: {
            /**
             * @description Public key signature algorithm
             * @enum {string}
             */
            algorithm: "ed25519" | "ecdsa-p256" | "rsa-pss-2048";
            /** @description Base64-encoded Nexus public key */
            public_key: string;
        };
        Manifest: components["schemas"]["Manifest_V1"];
        Manifest_V1: {
            /** @description Manifest schema version. */
            version: string;
            /**
             * @description Unique identifier for the application
             * @example nexus.hiyocord.org
             */
            id: string;
            /** @description Name of the application */
            name: string;
            /**
             * Format: uri
             * @description URL to the application's icon
             */
            icon_url?: string | null;
            /** @description Description of the application */
            description?: string;
            /**
             * Format: uri
             * @description Base URL for the application
             */
            base_url: string;
            /** @description Application commands supported by the application */
            application_commands: {
                /** @description Global application commands */
                global: components["schemas"]["DiscordCommand"][];
                /** @description Guild-specific application commands */
                guild: (components["schemas"]["DiscordCommand"] & {
                    /** @description List of guild IDs where the command is available */
                    guild_id: string[];
                })[];
            };
            message_component_ids: string[];
            modal_submit_ids: string[];
            permissions?: components["schemas"]["Permission"][];
            /**
             * @description Public key signature algorithm for authentication
             * @default ed25519
             * @enum {string}
             */
            signature_algorithm: "ed25519" | "ecdsa-p256" | "rsa-pss-2048";
            /** @description Base64-encoded public key for verifying requests from this service worker */
            public_key: string;
        };
        Permission: {
            /** @enum {string} */
            type: "DISCORD_BOT";
        } | {
            /** @constant */
            type: "DISCORD_API_SCOPE";
            /**
             * @description 許可するDiscord APIエンドポイントとHTTPメソッドの組み合わせ
             * @example {
             *       "/channels/{channel_id}/messages": [
             *         "POST"
             *       ],
             *       "/channels/{channel_id}/messages/{message_id}": [
             *         "GET",
             *         "PATCH",
             *         "DELETE"
             *       ],
             *       "/guilds/{guild_id}/members/{user_id}": [
             *         "GET"
             *       ]
             *     }
             */
            scopes: {
                [key: string]: string[];
            };
        };
        /** @description A Discord application command object */
        DiscordCommand: components["schemas"]["ApplicationCommandCreateRequest"];
        /** @description A Discord interaction object */
        DiscordInteraction: {
            /** @description Type of interaction */
            type?: number;
            /** @description Version of the interaction */
            version?: number;
            /** @description ID of the application */
            application_id?: string;
            /** @description Event data */
            event?: {
                /** @description Interaction data */
                data?: Record<string, never>;
            };
        };
        /** Format: int32 */
        ApplicationCommandOptionType: number & (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11);
        ApplicationCommandAttachmentOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 11;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
        };
        ApplicationCommandBooleanOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 5;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
        };
        /** Format: int32 */
        ChannelTypes: number & (1 | 3 | 0 | 2 | 4 | 5 | 10 | 11 | 12 | 13 | 14 | 15);
        ApplicationCommandChannelOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 7;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            channel_types?: components["schemas"]["ChannelTypes"][] | null;
        };
        /** Format: int64 */
        Int53Type: number;
        ApplicationCommandOptionIntegerChoice: {
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            value: components["schemas"]["Int53Type"];
        };
        ApplicationCommandIntegerOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 4;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            autocomplete?: boolean | null;
            choices?: components["schemas"]["ApplicationCommandOptionIntegerChoice"][] | null;
            min_value?: null | components["schemas"]["Int53Type"];
            max_value?: null | components["schemas"]["Int53Type"];
        };
        ApplicationCommandMentionableOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 9;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
        };
        ApplicationCommandOptionNumberChoice: {
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            /** Format: double */
            value: number;
        };
        ApplicationCommandNumberOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 10;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            autocomplete?: boolean | null;
            choices?: components["schemas"]["ApplicationCommandOptionNumberChoice"][] | null;
            /** Format: double */
            min_value?: number | null;
            /** Format: double */
            max_value?: number | null;
        };
        ApplicationCommandRoleOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 8;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
        };
        ApplicationCommandOptionStringChoice: {
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            value: string;
        };
        ApplicationCommandStringOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 3;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            autocomplete?: boolean | null;
            min_length?: number | null;
            max_length?: number | null;
            choices?: components["schemas"]["ApplicationCommandOptionStringChoice"][] | null;
        };
        ApplicationCommandUserOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 6;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
        };
        ApplicationCommandSubcommandOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 1;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            options?: (components["schemas"]["ApplicationCommandAttachmentOption"] | components["schemas"]["ApplicationCommandBooleanOption"] | components["schemas"]["ApplicationCommandChannelOption"] | components["schemas"]["ApplicationCommandIntegerOption"] | components["schemas"]["ApplicationCommandMentionableOption"] | components["schemas"]["ApplicationCommandNumberOption"] | components["schemas"]["ApplicationCommandRoleOption"] | components["schemas"]["ApplicationCommandStringOption"] | components["schemas"]["ApplicationCommandUserOption"])[] | null;
        };
        ApplicationCommandSubcommandGroupOption: {
            /**
             * Format: int32
             * @enum {integer}
             */
            type: 2;
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description: string;
            description_localizations?: {
                [key: string]: string;
            } | null;
            required?: boolean | null;
            options?: components["schemas"]["ApplicationCommandSubcommandOption"][] | null;
        };
        /** Format: int32 */
        InteractionContextType: number & (0 | 1 | 2);
        /** Format: int32 */
        ApplicationIntegrationType: number & (0 | 1);
        /** Format: int32 */
        ApplicationCommandHandler: number;
        /** Format: int32 */
        ApplicationCommandType: number & (1 | 2 | 3 | 4);
        ApplicationCommandCreateRequest: {
            name: string;
            name_localizations?: {
                [key: string]: string;
            } | null;
            description?: string | null;
            description_localizations?: {
                [key: string]: string;
            } | null;
            options?: (components["schemas"]["ApplicationCommandAttachmentOption"] | components["schemas"]["ApplicationCommandBooleanOption"] | components["schemas"]["ApplicationCommandChannelOption"] | components["schemas"]["ApplicationCommandIntegerOption"] | components["schemas"]["ApplicationCommandMentionableOption"] | components["schemas"]["ApplicationCommandNumberOption"] | components["schemas"]["ApplicationCommandRoleOption"] | components["schemas"]["ApplicationCommandStringOption"] | components["schemas"]["ApplicationCommandSubcommandGroupOption"] | components["schemas"]["ApplicationCommandSubcommandOption"] | components["schemas"]["ApplicationCommandUserOption"])[] | null;
            default_member_permissions?: number | null;
            dm_permission?: boolean | null;
            contexts?: components["schemas"]["InteractionContextType"][] | null;
            integration_types?: components["schemas"]["ApplicationIntegrationType"][] | null;
            handler?: null | components["schemas"]["ApplicationCommandHandler"];
            type?: null | components["schemas"]["ApplicationCommandType"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
